language: node_js
node_js:
 - 10
 - 11
 - node
env:
  - DEFAULT_NODE_VERSION=10
    CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_script:
  - npm run build

after_success:
  - if [ "$TRAVIS_NODE_VERSION" == "$DEFAULT_NODE_VERSION" ]; then
      npm install coveralls;
      node_modules/.bin/jest --coverage --coverageReporters=text-lcov |
        node_modules/.bin/coveralls;
    fi
