language: node_js
node_js:
 - 10
 - 11
 - 12
 - 13
 - lts/*
 - node
env:
  - DEFAULT_NODE_VERSION=12

before_script:
  - npm run build

after_success:
  - if [ "$TRAVIS_NODE_VERSION" == "$DEFAULT_NODE_VERSION" ]; then
      npm install coveralls;
      node_modules/.bin/jest --coverage --coverageReporters=text-lcov |
        node_modules/.bin/coveralls;
    fi
